@echo off
echo "                                           "
echo "@@@   @@@@@@    @@@@@@        @@@     @@@  "
echo "@@@  @@@@@@@   @@@@@@@@      @@@@    @@@@  "
echo "@@!  !@@            @@@     @@!@!   @@@!!  "
echo "!@!  !@!           @!@     !@!!@!     !@!  "
echo "!!@  !!@@!!       !!@     @!! @!!     @!@  "
echo "!!!   !!@!!!     !!:     !!!  !@!     !@!  "
echo "!!:       !:!   !:!      :!!:!:!!:    !!:  "
echo ":!:      !:!   :!:       !:::!!:::    :!:  "
echo " ::  :::: ::   :: :::::       :::     :::  "
echo ":    :: : :    :: : :::       :::      ::  "
echo "                                           "
echo " Welcome to IS241 Turtle Shell Development "
echo "           Secret Development UI           "
echo "Make a Selection:                          "
echo "1. Start Backend                           "
echo "2. Build Docker Containers and Deploy      "
echo "3. Start Development Server                "
echo "4. RAVE MODE                               "
set 